= dibs - Docker image build system
// vim: ts=4 sts=4 sw=4 et ai colorcolumn=79 tw=78 :
:toc:
:toc-placement!:

Dibs makes it simple to turn code into Docker images.

To some extent, it can be seen as an alternative to
using a https://docs.docker.com/engine/reference/builder/[Dockerfile],
with the difference that `dibs` provides finer control over the
different phases and makes it easier to land on a trimmed image.

*THIS DOCUMENT IS CURRENTLY OBSOLETE AND NEEDS REWORKING AFTER REFACTORING*

toc::[]

== But... _why_?

First things first: why `dibs`? The main need is to pack a Docker
container image starting from some code, much like what can be done with
a https://docs.docker.com/engine/reference/builder/[Dockerfile]… let’s
look at a few problems and how `dibs` addresses them.

=== Trimming Container Images

Just putting the code inside a container is not sufficient, because…

* … it probably needs a runtime environment (Perl, Java, Python, …)
inside the image too
* … it might need additional pre-requisites in form of other software or
libraries, often provided by the underlying Linux distribution in the form of
packages
* … it might need to have some parts compiled or undergo a _build_
process
* … it will probably need the container to be set so that the invocation
of the program is eased.

The build process usually requires tools (like a compiler, C,
development versions of libraries, etc.) that are rarely needed during
the runtime phase. With a single
https://docs.docker.com/engine/reference/builder/[Dockerfile], there are
two choices:

* keep the tools around, or get rid of them while still having a _fat_
image.footnote:[ Due to how filesystem overlays work, what is _deleted_ in a layer
only hides it from lower layers, but the space is still needed];
* install the tools and remove them in the same phase of the
https://docs.docker.com/engine/reference/builder/[Dockerfile], thus
making it difficult to cache or pinpoint the tools themselves.

The idea behind `dibs` is that the path from the code to the Docker
image is not necessarily _linear_ and might be walked through different lanes,
or _phases_

- each phase runs a sequence of operations that stack upon a container image
  much like a https://docs.docker.com/engine/reference/builder/[Dockerfile]
  does;
- different phases share artifacts around through shared directories; only the
- containers of interest are saved as images, others are thrown away.

As an example, a common patter is to divide the composition of an image into
two phases, one where artifacts are compiled (through compilation and build
tools) and one where these artifacts are installed along with runtime
components. For this reason, two base images can be setup.footnote:[For
example, using `dibs` itself.] and used in two different phases, one for
building and one for bundling the final artifact.

....
  _____________     +--------------+
 /             \    |              | - start from "build"-ready image, with
 | Shared dirs |----| Build Phase  |   compiler & other build tools inside
 | ----------- |    |              | - compile in container
 |             |    +--------------+ - save in cache
 |       src - |    
 |     cache - |    +--------------+
 |       env - |    |              | - start from "runtime"-ready image
 |       ... - |----| Bundle Phase | - copy artifacts from cache
 \_____________/    |              |   to destination
                    +--------------+ - set up entry point
....

In this way, _build_ operations can be performed from a _heavier_ container
image (the one with the build tools), while the _bundle_ operation relies on a
_leaner_ starting container image (the one with just the runtime), providing a
_leaner_ result.

=== Reuse of operations

Another common problem with
https://docs.docker.com/engine/reference/builder/[Dockerfile]s has to do
with how container images are customized, e.g. to execute build/bundle
operations.

The https://docs.docker.com/engine/reference/builder/#run[RUN] directive in
the https://docs.docker.com/engine/reference/builder/[Dockerfile] is very
powerful, but it allows executing either direct commands or some
script/program that are available inside the container during its
construction. While very powerful (it’s actually all that is strictly needed),
it’s quite difficult to reuse operations consistently.

`dibs` allows defining _packs_ of operations{blank}footnote:[The name is
inspired to https://www.heroku.com/[Heroku]'s buildpacks, but the semantics is
nowadays very different.] in many different ways, which include grouping them
in a git repository that can be shared across multiple projects. An example of
such a repository is
https://github.com/polettix/dibspack-basic[dibspack-basic].

== Basics

The basic metaphor used in Dibs is inspired to drawing (because the aim is to
generate... an image). To generate an image, multiple _actions_ are available:

- setting the starting point for an image is to _prepare_ it, much like the
  https://docs.docker.com/engine/reference/builder/#from[FROM] directive in
  the https://docs.docker.com/engine/reference/builder/[Dockerfile];
- a single operation step performed inside a container is a _stroke_. It can
  be thought as a single 'RUN`
  https://docs.docker.com/engine/reference/builder/#run[RUN] directive in the
  https://docs.docker.com/engine/reference/builder/[Dockerfile];
- finalizing an image is to _frame_ it (there is no equivalent operation in
  the https://docs.docker.com/engine/reference/builder/[Dockerfile]);
- collecting multiple actions together is to create a _sketch_ (it can contain
  other __sketch__es itself).

When run, `dibs` goes through two main phases, namely the setup and the
execution of actions:

- in the setup phase collects all available information for the specific run.
  It merges together different sources (command line parameters, environment
  variables, and the configuration file that will be described below), making
  also sure that the source code is fetched and made ready for operating the
  different steps;
- in the execution phases, `dibs` executes the required actions. This may end
  up in an image or not, depending on the needs.

The operations in a _stroke_ are performed through __dibspack__s (or simply
__pack__s). They are the specification of where _something_ can be found, most
probably a program or a group of programs that can be executed inside the
container.footnote:[Packs can be used also to locate other configuration
files, although this feature is yet to be introduced.]

All actions (and something more) are defined inside a _configuration
file_,footnote:[This might turn in multiple ones in a future release.], whose
structure will be described below.

Dibs elects a directory as a base camp for its operations, called the _project
directory_. Depending on the specific configuration, it defaults to a `dibs`
sub-directory of the current directory, or to the current directory itself.
The configuration file and other directories _shared_ across all stroke
executions are related to the _project directory_, and are:

- `src`: where the source (code, prerequisites, etc.) is made available,
  read-write;
- `cache`: a convenience area where build artifacts can be stored, e.g. to pass
  them across different strokes or entire phases. Available in read-write mode
  inside the container
- `env` and `envile`: read-only directories where data is passed from the
  outside. The former can be used to set up data from the user, the latter is
  used by `dibs` itself to set them in the form of keys (filename) associated
  to data (the contents of the files);
- `pack`, `auto/open`: where dibpacks are stored (the former local to the
  specific project, the latter generated automatically by `dibs` from
  remote/dynamic dibspacks).

== Examples

It's better to start looking at a couple of examples to better understand how
`dibs` works.

=== Development Mode, Initial Example

The basic mode of operations of `dibs` is _development mode_. As the name
implies, it is best used when developing the software and generating the
container image during development itself (e.g. as a developer).

The example assumes the following layout of files and directories:

.directory layout
----
.git/
    [...]
app.pl
cpanfile
dibs.yml
prereqs/
    alpine.build
    alpine.bundle
----

where:

- `.git` indicates that the whole project is tracked with `ŋit`;
- `app.pl` is a Perl program;
- `cpanfile` details the module dependencies of the Perl program;
- `dibs.yml` is `dibs`'s configuration file;
- `prereqs` is a directory for storing pre-requirements files
- `alpine.build` and `alpine.bundle` are two programs that, when executed
  inside a container, make sure to install the OS packages needed by `app.pl`
  or any of the modules that will be installed by `cpanfile`. Each program
  installs the requirements for a specific phase, in this case `build` and
  `bundle` represent the build phase (where artifacts are generated) and the
  bundle phase (where the artifacts are put in place along with the runtime
  environment).

The `dibs.yml` configuration file in this example is the following (note: this
is quite simple at this stage, additional features will be shown later):

.dibs.yml
[source,yaml]
----
name: exadev                            # # <1>
packs:                                  # # <2>
    basic:
        type: git
        origin: https://github.com/polettix/dibspack-basic.git
actions:
    default: [build, bundle]            # # <3>
    prereqs:                            # # <4>
      pack: basic
      path: prereqs
    build:                              # # <5>
        envile:                         # # <6>
            DIBS_PREREQS: build
        actions:
            - from: 'alpine:3.6'        # # <7>
            - prereqs                   # # <8>
            - name: compile             # # <9>
              pack: basic
              path: perl/build
            - name: save compiled artifacts in cache
              pack:
                run: |                  # # <10>
                    #!/bin/sh
                    src_dir="$(cat DIBS_SRC_DIR)"
                    cache_dir="$(cat DIBS_CACHE_DIR)"
                    dst_dir="$cache_dir/app"
                    set -e
                    rm -rf "$target"
                    mkdir -p "$target"
                    cp -a "$src_dir/app.pl" "$target"
                    cp -a "$src_dir/local" "$target"
    bundle:
        envile:
            DIBS_PREREQS: bundle
        actions:
            - from: 'alpine:3.6'
            - prereqs
            - name: put artifacts in place
              pack:
                run: |
                    #!/bin/sh
                    cache_dir="$(cat DIBS_CACHE_DIR)"
                    src_dir="$cache_dir/app"
                    dst_dir="/app"
                    rm -rf "$dst_dir"
                    cp -a "$src_dir" "$dst_dir"
              commit:                   # # <11>
                entrypoint: []
                cmd: ['/bin/sh', '-l']
            - name: save bundled image  # # <12>
              image_name: exadev
              tags: ['latest', '0.3']
----
<1> the name is used for temporary images
<2> it's possible to define named packs and refer to them later
<3> an _action_ named `default` is what is executed... by default
<4> this is the specification of a _stroke_, based on the `basic` _pack_.
<5> this is the specification of a _sketch_ (because it contains a list of
__action__s)
<6> __envile__s are similar to environment variables, but less invasive
<7> this is equivalent to FROM in a Dockerfile
<8> this "calls" the `prereqs' _stroke_ defined elsewhere (above in this case)
<9> this is a _stroke_ where a name is assigned explicitly, so that it will be
shown when executed
<10> this is an _immediate_ pack that is saved as a script and then executed
inside the container
<11> adding a `commit` sets additional traits of the image layer, e.g.
`entrypoint`, `cmd`, `user`, ...
<12> this is a _frame_, i.e. the actual saving of an image

Running `dibs` in this case is as simple as going in the root directory of the
code and run:

----
$ dibs
----

This will execute the `default` _sketch_, which is comprised of two actions
`build` and `bundle`. They will be executed both, in the specific order. They
are both __sketch__es themselves (they both contain a list of actions).

Sketch `build` starts from a basic image (an Alpine Linux, release 3.6) and
executes three `RUN`-like actions on top of it, in the specific order:

- installation of pre-requisites (calling the `prereqs` _stroke_ defined
  above). The script that install pre-requisites uses the variable
  `DIBS_PREREQS` to select the right prerequisites script, which will be
  `prereqs/alpine.build` in this case.
- "compilation" of the Perl code. This reduces to the installation of modules
  as specified in file `cpanfile`
- save of `app.pl` (main program) and `local` (where installed modules are
  placed) inside the cache directory (in particular, in the `app`
  sub-directory)

Each step is executed "on top" of the previous one, just like several `RUN`
directives in a Dockerfile are executed.

Sketch `build` does not include a _frame_ action, so the final container is
removed and not saved.

Sketch `bundle` is similar to `build`, but also different:

- starts from the same base image `alpine:3.6`
- install pre-requisites. In this case `DIBS_PREREQS` is set to `bundle`, so
  the prerequisites program that will be run is `prereqs/alpine.bundle`. This
  is an example of reuse, because the same script (`prereqs` in the `basic`
  pack) is used to obtain different results in different conditions;
- artifacts are copied from the cache to the final target destination (in
  `/app`). This is the last "layer" that is added to the image, so there is
  also the specification of a `commit` section to set the `entrypoint` and the
  `cmd` to be executed by default.
- the last action of the sketch is a _frame_ that saves the final container as
  an image with two tags: `exadev:latest` and `exadev:0.3`.

=== Development Mode, Explicit Pinpointing

The previous example showed an example where _build_ and _bundle_ are
separated, but as a matter of fact it does not provide a real advantage in
terms of execution time, because the installation of prerequisites on top of a
basic image is always performed (`dibs` does not include implicit
caching/pinpointing of intermediate containers like Dockerfiles).

It's possible to expand the example to limit the amount of repeated work, like
shown in the following example.

.dibs.yml
[source,yaml]
----
name: exadev
packs:
    basic:
        type: git
        origin: https://github.com/polettix/dibspack-basic.git
actions:
    default: [build, bundle]
    prereqs:
      pack: basic
      path: prereqs
    builder:                               # # <1>
        envile:
            DIBS_PREREQS: build
        actions:
            - from: 'alpine:3.6'
            - prereqs
            - name: save builder base image
              image_name: builder
              tags: '1.0'
    build:
        actions:
            - from: 'builder:1.0'          # # <2>
            - name: compile
              pack: basic
              path: perl/build
            - name: save compiled artifacts in cache
              pack:
                run: |
                    #!/bin/sh
                    src_dir="$(cat DIBS_SRC_DIR)"
                    cache_dir="$(cat DIBS_CACHE_DIR)"
                    dst_dir="$cache_dir/app"
                    set -e
                    rm -rf "$target"
                    mkdir -p "$target"
                    cp -a "$src_dir/app.pl" "$target"
                    cp -a "$src_dir/local" "$target"
    bundler:
        envile:
            DIBS_PREREQS: bundle
        actions:
            - from: 'alpine:3.6'
            - prereqs
            - name: save bundler base image
              image_name: bundler
              tags: '1.0'
    bundle:
        actions:
            - from: 'bundler:1.0'
            - name: put artifacts in place
              pack:
                run: |
                    #!/bin/sh
                    cache_dir="$(cat DIBS_CACHE_DIR)"
                    src_dir="$cache_dir/app"
                    dst_dir="/app"
                    rm -rf "$dst_dir"
                    cp -a "$src_dir" "$dst_dir"
              commit:
                entrypoint: []
                cmd: ['/bin/sh', '-l']
            - name: save bundled image
              image_name: exadev
              tags: ['latest', '0.3']
----
<1> Former `build` is divided into parts, this is the first and yields an
image that is saved permanently as `builder:1.0`
<2> The image is then used as a base for the `build` stroke.

In this example, former `build` sketch has been broken down into two sketches,
the first one (`builder`) installing the pre-requisites and saving a base
image that is suitable for building (`builder:1.0`) and is thus used as the
starting point for sketch `build`. A similar split has been performed onto
`bundle`, extracting the pre-requisites part into `bundler`.

To generate the new base images for building and bundling the following
command is run:

----
$ dibs builder bundler
# generates builder:1.0 and bundler:1.0
----

After this step has been run, these images are used as bases for the new
`build` and `bundle` steps, so when the following command is run:

----
$ dibs build bundle
----

the prerequisites installation is not performed any more, saving time.

=== Robust Pinpointing

The split in the previous example was possible because of the assumption that
pre-requisites change very seldom in a project (with the possible exception of
the initial days). Anyway, it's possible that the pre-requisites have to
change from time to time, in which case it's necessary to regenerate the base
images to include them, which might be easily overlooked.

At the expense of an additional layer, though, it's possible to repeat the
`prereqs` stroke inside the `build` and the `bundle` strokes; these will
mostly resolve into nothing (i.e. no change) unless an addition is put in the
prerequisites, in which case the addition will be honored. The following
`dibs.yml` implements this approach.

.dibs.yml
[source,yaml]
----
name: exadev
packs:
    basic:
        type: git
        origin: https://github.com/polettix/dibspack-basic.git
actions:
    default: [build, bundle]
    prereqs:
      pack: basic
      path: prereqs
    builder:
        envile:
            DIBS_PREREQS: build
        actions:
            - from: 'alpine:3.6'
            - prereqs
            - name: save builder base image
              image_name: builder
              tags: '1.0'
    build:
        envile:                            # # <1>
            DIBS_PREREQS: build
        actions:
            - from: 'builder:1.0'
            - prereqs                      # # <2>
            - name: compile
              pack: basic
              path: perl/build
            - name: save compiled artifacts in cache
              pack:
                run: |
                    #!/bin/sh
                    src_dir="$(cat DIBS_SRC_DIR)"
                    cache_dir="$(cat DIBS_CACHE_DIR)"
                    dst_dir="$cache_dir/app"
                    set -e
                    rm -rf "$target"
                    mkdir -p "$target"
                    cp -a "$src_dir/app.pl" "$target"
                    cp -a "$src_dir/local" "$target"
    bundler:
        envile:
            DIBS_PREREQS: bundle
        actions:
            - from: 'alpine:3.6'
            - prereqs
            - name: save bundler base image
              image_name: bundler
              tags: '1.0'
    bundle:
        envile:                            # # <1>
            DIBS_PREREQS: bundle
        actions:
            - from: 'bundler:1.0'
            - prereqs                      # # <2>
            - name: put artifacts in place
              pack:
                run: |
                    #!/bin/sh
                    cache_dir="$(cat DIBS_CACHE_DIR)"
                    src_dir="$cache_dir/app"
                    dst_dir="/app"
                    rm -rf "$dst_dir"
                    cp -a "$src_dir" "$dst_dir"
              commit:
                entrypoint: []
                cmd: ['/bin/sh', '-l']
            - name: save bundled image
              image_name: exadev
              tags: ['latest', '0.3']
----
<1> The `prereqs` program relies upon the `DIBS_PREREQS` variable, so it has
to be set whenever `prereqs` will be used.
<2> The `prereqs` stroke is re-introduced as the first step in both `build`
and `bundle`. Most of the times this will be a no-op.

Running the `prereqs` step can anyway draw time from the build/bundle process
though, so in all cases in which it can be skipped it can be useful to avoid
it. The following example does some refactoring to add `buildq` (i.e.
the _quick_ version of `build`), leaving out `bundleq` (which can undergo a
similar transformation).

.dibs.yml
[source,yaml]
----
name: exadev
packs:
    basic:
        type: git
        origin: https://github.com/polettix/dibspack-basic.git
actions:
    default: [build, bundle]
    prereqs:
        pack: basic
        path: prereqs
    builder:
        envile:
            DIBS_PREREQS: build
        actions:
            - from: 'alpine:3.6'
            - prereqs
            - name: save builder base image
              image_name: builder
              tags: '1.0'
    build_basics:                     # # <1>
        - name: compile
          pack: basic
          path: perl/build
        - name: save compiled artifacts in cache
          pack:
            run: |
                #!/bin/sh
                src_dir="$(cat DIBS_SRC_DIR)"
                cache_dir="$(cat DIBS_CACHE_DIR)"
                dst_dir="$cache_dir/app"
                set -e
                rm -rf "$target"
                mkdir -p "$target"
                cp -a "$src_dir/app.pl" "$target"
                cp -a "$src_dir/local" "$target"
    build:                            # # <2>
        envile:
            DIBS_PREREQS: build
        actions:
            - from: 'builder:1.0'
            - prereqs
            - build_basics
    buildq:                           # # <2>
        - from: 'builder:1.0'
        - build_basics
# ...
----
<1> `build_basics` is a new sketch that includes strokes to compile modules
and save artifacts in the cache
<2> the new artifact is used in both the `build` and `buildq` sketches,
avoiding repetitions


=== Directory Layouts

`dibs` sets the base in a _project directory_ where things are kept nicely.
There are a few ways the whole directory tree can be organized though.

By default there is the _development mode_, where the project directory is the
`dibs` sub-directory of the current directory:

....
<git-repo>
    - dibs
        - cache
        - dibspacks
        - [dibs.yml]
        - env
        - src
    - [dibs.yml]
....

This comes particularly handy when developing and the main directory is also
the root for a git repository; alternatively, it might also fit nicely within
a git bare repository.

The `dibs.yml` file contains the
configurations, and can be placed either in the git repo itself or inside the
`dibs` project directory.

An alternative setup is the so-called _alien mode_, which can be selected
through an option (`--alien`) and has the following layout:

....
<dibs-project-dir>
    - cache
    - dibspacks
    - dibs.yml
    - env
    - src
....

The assumption here is that the code to package is taken from somewhere else
or is already inside `src`. An example use case would be a team packaging
somebody else's repository. Again, there is a `dibs.yml` to keep al different
configurations.

Whatever the layout, anyway, the following directories are of interest:

* _project_ directory is a basecamp for `dibs` operations

* `src` is where the source code is or is put and then made available to
* containers

* `cache` is a read-write directory that is available through all steps
of a `dibs` run, as well as different invocations, and useful for passing
artifacts through the different stages

* `env` is a read-only directory that might be useful to have around

* `dibspacks` is where most of the dibspacks will be available (either
coded directly, or automatically downloaded via https://git-scm.com/[Git])

== Source

Depending on which _mode_ is set, the directory layout is different.

In _external_ mode (default), the layout is the following:

....
<PROJECT_DIR>
    - cache
    - dibs.yml
    - dibspacks
    - env
    - src
....

The `src` directory is assumed to be populated by some means, e.g. be
already there thanks to some external program, or fetched as part of a
_dibspack_’s operation (the source directory is mounted read-write). For
example, the
https://github.com/polettix/dibspack-basic/blob/master/git/fetch[git/fetch]
program can be used to fetch a remote https://git-scm.com/[Git]
repository, but it might also be that the development happens directly
inside `src`.

In _local_ mode (triggered with command-line option `--local` or its
shortcut alias `-l`), instead, the root is assumed to be the source
directory itself, so it’s assumed to be already there. This can be
useful when doing local development, for example, with local generation
of images.

== Dibspacks

Dibspacks are at the real core of `dibs`; it would be able to do very
little without.

We already touched upon what a dibspack is: a program to execute some task.
When run, a _dibspack_ is passed some command line arguments. The first three
are _always_ the same, namely (in order):

* the absolute path to the _source_ directory from within the container;
* the absolute path to the _cache_ directory, from within the container;
* the absolute path to the _env_ directory, from within the container.

It’s the same as what is provided to the `build` program of a
https://devcenter.heroku.com/articles/buildpacks[buildpack]. `dibs` also
allows passing additional arguments though, whose definition and
semantics are specific to each dibspack; these additional parameters can be
thought as the parameters normally passed to a custom function.

Dibspacks can be located in many different positions:

* within the `dibs.yml` file itself
* inside the `dibspacks` directory (that is also available inside the
container, although its position is not passed on the command line)
* in some location inside the source directory
* in a git repository, either local or remote

Depending on the type of dibspack, `dibs` will first fetch the
associated code and then run it, all automatically. For a collection of
basic dibspack, it’s possible to look at the
https://github.com/polettix/dibspack-basic[dibspack-basic] repository. A
simple example program might be the following (assuming that the build
tools are already available in the container):

....
#!/bin/sh
src_dir="$1"
cache_dir="$2"

# make any error complain loudly and fail the dibspack
set -e

cd "$src_dir"
rm -rf local
cp -a "$cache_dir/local" .
carton install --deployment
rm -rf "$cache_dir/local"
cp -a local "$cache_dir"
....

`dibs` supports different ways for you to configure the location of
dibspacks, which should cover a wide range of needs. They are documented
in the documentation for `dibs` so the full explanation will not be
repeated here.

Dibspacks taken from `git` are saved inside the `dibspacks/git`
directory. Although it’s not mandatory, it’s probably better to put
_local_ dibspacks inside another sub-directory, e.g. `dibspacks/local`
or so.

Dibspacks of the _immediate_ type (i.e. where the program is provided
inside `dibs.yml` itself) are saved inside `dibspacks/immediate`, so in
this case too it’s wise to avoid hitting that.

Dibspack programs are invokes like this:

....
<program> <src> <cache> <env> [args from dibspack configuration...]
....

Example:

....
whatever.sh /tmp/src /tmp/cache /tmp/env what ever
....

The first three arguments are paths to the associated directories in the
project directory, but ``seen'' from inside the container. In
particular:

* `src` and `cache` are available in read-write mode;
* `env` is always set read-only.

The directories are usually mounted under `/tmp` like in the example, so
you should avoid using them otherwise. This might change in the future.
Additionally, the `dibspacks` directory is mounted too as
`/tmp/dibspacks`, read-only; you should not use this directory directly,
unless you know what you are doing and accept that this may change in
the future.

A full selection of dibspacks can be found in
https://github.com/polettix/dibspack-basic[dibspack-basic].

== Configuration

The configuration is kept, by default, inside YAML file `dibs.yml`; it’s
possible to change this though, so that multiple alternative
configurations can be kept in the same place.

The structure is described in detail in `dibs`’s documentation, so we
will concentrate on examples here.

A rather simple but possibly effective configuration file is the
following:

....
---
name: example-project
defaults:
    dibspacks:
        basic:
            type:   git
            origin: https://github.com/polettix/dibspack-basic.git
            user:   user
        prereqs:
            type:   git
            origin: https://github.com/polettix/dibspack-basic.git
            path:   prereqs
            user:   root
steps:
    - build
    - bundle
definitions:
    build:
        from: fat-build-image:tag
        dibspacks:
            - default: prereqs
              args: build
            - default: basic
              path: perl/build
            - default: src
              user: user
              path: dibs/copy-app-into-cache.sh
    bundle:
        from: lean-running-image:tag
        keep: yes
        entrypoint: ['/runner']
        cmd: []
        tags:
            - latest
        dibspacks:
            - default: prereqs
              args: bundle
            - default: src
              user: user
              path: dibs/copy-app-from-cache.sh
....

There are a few assumptions in the `dibs.yml` file above, but it can
actually work if:

* images `fat-build-image:tag` and `lean-running-image:tag` already
exist and contain, respectively, the build tools and the runtime
elements (including a `/runner` program that is used as entry-point)
* the source directory contains a `dibs` sub-directory and the relevant
scripts inside, doing what the advertise in their names.

In this way it’s possible to prepare (and maintain) a build and a bundle
images, and leverage them for doing the actual needed work, generating a
lean output Docker image.

== Running

When run, `dibs` looks for the steps to be executed, and runs them.

In particular, each step is run stacking on top of an evolving
container, much like in the
https://docs.docker.com/engine/reference/builder/[Dockerfile] case.
Whether to keep or ditch the end result is a choice that is made inside
the `dibs.yml` file through the `keep` option.

Different steps are run one after the other, but in independent
containers that potentially root from different starting images, like in
the example above in the configuration section.

The documentation for `dibs` has the detail on all command line options,
although it’s probably important to remember that `--local` allows
selecting between the _local_ mode (when present) or the _external_ mode
(when absent from the command line).

This allows implementing many different workflows, e.g.:

* define one or more _build_ phases that leverage images/dibspacks that
include build tools, like a compiler;
* save the outcome of that/those phases in the `cache` directory
* define a _bundle_ phase where that outcome is fit inside a _release_
image that only contains the needed tools for running (but does not
include building tools)

== Examples

`dibs` allows taking a flexible approach to building images, which might
be overwhelming. Here are a few examples that might apply in different
situations.

=== `dibs` itself

This was the `dibs.yml` file for building the `dibs` image at some stage
of its life:

....
01  ---
02  name: dibs
03  logger:
04     - Stderr
05     - log_level
06     - info
07  steps:
08     - build
09     - bundle
10  defaults:
11     variables:
12        - &base_image 'alpine:3.6'
13        - &version 'DIBSPACK_SET_VERSION="0.001972"'
14     dibspack:
15        basic:
16           type:   git
17           origin: https://github.com/polettix/dibspack-basic.git
18           user:   user
19        prereqs:
20           type:   git
21           origin: https://github.com/polettix/dibspack-basic.git
22           path:   prereqs
23           user:   root
24        user: &user
25           type: src
26           name: add user and enable for docker
27           user: root
28           path: dibspacks/user-docker.sh
29  definitions:
30     builder:
31        from: *base_image
32        keep: yes
33        name: 'dibs-builder'
34        tags: [ 'latest' ]
35        dibspacks:
36           - *user
37           - default: prereqs
38             args: build
39     runner:
40        from: *base_image
41        keep: yes
42        name: 'dibs-runner'
43        tags: [ 'latest' ]
44        dibspacks:
45           - *user
46           - default: prereqs
47             args: bundle
48     build:
49        from: 'dibs-builder:latest'
50        keep: no
51        dibspacks:
52           - default: prereqs
53             args: build
54           - 'src:dibspacks/src-in-app.sh'
55           - default: basic
56             path: perl/build
57             args: ['/app', *version]
58           - default: basic
59             path: install/with-dibsignore
60             args: '--src /app --dst @path_cache:perl-app'
61     bundle:
62        from: 'dibs-runner:latest'
63        keep: yes
64        name: dibs
65        tags: [ 'latest' ]
66        entrypoint: [ '/dockexec', 'user', '/profilexec', '/app/bin/dibs' ]
67        cmd: [ '--help' ]
68        dibspacks:
69           - default: prereqs
70             args: bundle
71           - default: basic
72             user: root
73             path: wrapexec/install
74             args: ['dockexec', 'profilexec']
75           - default: basic
76             path: install/plain-copy
77             args: '@path_cache:perl-app /app'
78             user: root
....

This leverages both remote and local dibspacks. The following
sub-sections add some considerations on the above example.

==== Defaults

The `defaults` section has two sub-sections, one (`variables`), mostly
used internally in a _YAML-way_, the other one (`dibspack`) consumed by
`dibs`:

* `variables` concentrates some values that can be reused later in the
YAML file; for this reason, its items are preceded by a label
(`base_mage` and `version`). Concentrating values here allows easier
maintenance and enhances readability. The `version` _variable_ is set in
the way it will eventually consumed, but this depends on the dibspack of
course.
+
....
11       variables:
12          - &base_image 'alpine:3.6'
13          - &version 'DIBSPACK_SET_VERSION="0.001972"'
....
+
There’s more to it anyway, although not visible in the example; in
particular, it’s possible to set some _expansions_, like in the
following example:
+
....
variables:
   - &version_major           '0'
   - &version_minor           '1'
   - &version_patch           '1'
   - function: &version
      ['join', '.', *version_major, *version_minor, *version_patch]
   - function: &version_maj_min
      ['join', '.', *version_major, *version_minor]
....
+
The `function` associative arrays are expanded evaluating the function
in the array (if supported, currently on `join` is).
* `dibspack` sets a few commodity configurations for later reuse inside
definitions. Most of the activities are performed leveraging
https://github.com/polettix/dibspack-basic[dibspack-basic], so it’s
easier to define it here once and for all. `prereqs` will be reused by
all steps, so it gets a _factored_ definition too. Last, both the base
images `builder` and `runner` will define a `user` to avoid running as
`root`, so the relevant definitions are factored here as well. In this
case, the default is also assigned a YAML label for later direct reuse.
+
....
14       dibspack:
15          basic:
16             type:   git
17             origin: https://github.com/polettix/dibspack-basic.git
18             user:   user
19          prereqs:
20             type:   git
21             origin: https://github.com/polettix/dibspack-basic.git
22             path:   prereqs
23             user:   root
24          user: &user
25             type: src
26             name: add user and enable for docker
27             user: root
28             path: dibspacks/user-docker.sh
....

==== Structure

The definition contains four definitions, two for _base images_, one for
building the code and the last one for bundling the final output image.

* `builder` is the base image used for building. The final container is
preserved (`keep` set to `yes`) but it is assigned a specific name
(`dibs-builder`) to avoid overlapping with the main image of interest.
The main goal if this image is to pre-bake most of the requirements
(which should change slowly in time) and make sure there is the right
user in the image.
+
....
30       builder:
31          from: *base_image
32          keep: yes
33          name: 'dibs-builder'
34          tags: [ 'latest' ]
35          dibspacks:
36             - *user
37             - default: prereqs
38               args: build
....
* `runner` serves a purpose much similar to `builder`, but will be used
as base for the bundled image by definition in `bundle`. Note that the
pre-baking of pre-requisites concentrates on `bundle` instead of
`build`; this allows the `prereqs` dibspack inside
https://github.com/polettix/dibspack-basic[dibspack-basic] to pick the
right pre-requisites for running instead of building.
+
....
39       runner:
40          from: *base_image
41          keep: yes
42          name: 'dibs-runner'
43          tags: [ 'latest' ]
44          dibspacks:
45             - *user
46             - default: prereqs
47               args: bundle
....
* `build` leverages the _fatter_ image output from `builder` to do the
compilation and building steps. It’s the most complex of the
definitions, and also the one whose container is eventually thrown away,
thanks to the call to `install/with-dibsignore` that saves the relevant
parts in the cache.
+
....
48       build:
49          from: 'dibs-builder:latest'
50          keep: no
51          dibspacks:
52             - default: prereqs
53               args: build
54             - 'src:dibspacks/src-in-app.sh'
55             - default: basic
56               path: perl/build
57               args: ['/app', *version]
58             - default: basic
59               path: install/with-dibsignore
60               args: '--src /app --dst @path_cache:perl-app'
....
* `bundle` starts from where `build` left off, but this time in the
_leaner_ image output by `runner`. The installation of the `dockexec`
and `profilexec` programs might be moved inside the `runner` as it’s
something that will not change significatively in time; here it’s left
to enhance readability when setting the `entrypoint`.
+
....
61       bundle:
62          from: 'dibs-runner:latest'
63          keep: yes
64          name: dibs
65          tags: [ 'latest' ]
66          entrypoint: [ '/dockexec', 'user', '/profilexec', '/app/bin/dibs' ]
67          cmd: [ '--help' ]
68          dibspacks:
69             - default: prereqs
70               args: bundle
71             - default: basic
72               user: root
73               path: wrapexec/install
74               args: ['dockexec', 'profilexec']
75             - default: basic
76               path: install/plain-copy
77               args: '@path_cache:perl-app /app'
78               user: root
....

The `builder` and `runner` definitions might be avoided and merged
respectively inside `build` and `bundle`. Keeping them separate allows
reducing the time for installing pre-requisites, which is a form of
controlled caching.

==== Steps

The `steps` section only runs for `build` and `bundle` because these are
the _recurrent_ operations. These two definitions leverage on the
presence of `dibs-builder:latest` and `dibs-runner:latest` though, so
they will need to be generated (or pulled) before this `dibs.yml` can be
used out the box.

Generating the images is easy anyway, because the `dibs.yml` file
contains the relevant definitions:

....
$ dibs --local builder,runner
....

After this, the regular _build&bundle_ process can be run simply as
this:

....
$ dibs --local
....

==== Shortcut syntax for dibspacks

Line 54 shows a shortcut syntax for including a dibspack in the list for
a definition:

....
48     build:
49        from: 'dibs-builder:latest'
50        keep: no
51        dibspacks:
52           - default: prereqs
53             args: build
54           - 'src:dibspacks/src-in-app.sh'
55           - default: basic
56             path: perl/build
57             args: ['/app', *version]
58           - default: basic
59             ...
....

The shortcut syntax is equivalent to the following:

....
# type is src, i.e. the path below is relative to the source
type: src
path: dibspacks/src-in-app.sh
....

This syntax is available also for types `project` and `src`.

Dibspacks of type `git` have a shortcut syntax too, which amounts to
providing just the URI to the repository (optionally followed by `#` and
the ref to checkout). In this case, the repository is supposed to
contain a program called `operate` in the root directory, which will
eventually be called as entry point of the dibspack.

Dibpacks of type `immediate` have the following _shortcut_ syntax, which
is not in the form of a simple string but a very tight associative array
instead:

....
build:
  dibspacks:
    - run: |
        #!/bin/sh
        printf '%s\n' 'Hello, world!'
    ...
....

The above example is equivalent to the following:

....
build:
  dibspacks:
    - type: immediate
      program: |
        #!/bin/sh
        printf '%s\n' 'Hello, world!'
    ...
....

==== Providing `args` to a dibspack

The arguments passed to a dibspack during invocation are:

....
program src_dir cache_dir env_dir [other args..]
....

The _other args_ can be set using the `args` key in the associative
array defining the dibspack. This points to a list of elements, that can
be either plain scalars (e.g. strings or numbers), passed verbatim, or
associative array allowing you to retrieve some data from `dibs`.

If you’re just looking for a few examples, the following should all
work:

....
args:
  - path:               # referred to cache
      cache: perl
  - path_cache: perl    # ditto, shortcut
  - '@path_cache:perl'  # ditto, string-only shortcut
  - path_src: /prereqs  # referred to src, even with initial /
  - '@path_src:/prereqs' # ditto
  - path_env: /some
  - path_dibspacks: build
  - type: path          # ditto
    cache: perl
  - type: step_id       # key of step in definitions
  - type: step_name     # "step" field in definition, defaults to key
....

The arguments can also be provided as a single string, which is where
the string-shortcuts come handy. The following:

....
args: '@path_cache:perl-app /app'
....

is equivalent to:

....
args:
    - path:
        type: path
        cache: perl-app
    - '/app'
....

but much easier to type.

The _full_ way of setting a special parameter is like this:

....
args:
  - type: some_type
    this: that
    another: argument
....

The available `type`s are:

* `path`: allows to resolve a path within the container, referred to a
specific base directory. For example:
+
....
args:
  - path:
      cache: /whatever
....
+
is resolved to the `whatever` sub-directory of wherever the cache
directory happens to have been mounted inside the container. In addition
to `cache`, you can set paths relative to `dibspacks`, `env` and `src`.
* `step_id`: the identifiers of the dibspack inside the `definition`
associative array
* `step_name`: whatever was set as `step` parameter inside the dibspack
definition

Additionally, you can also use the shorthands `path_cache`,
`path_dibspacks`, `path_env` and `path_src`, which are turned into the
right `path` definition. For example, the following argument expansions
will provide the same path:

....
args:
  - path:
      cache: /whatever
  - path_cache: /whatever
....

It’s easy to forget to associate a value to `step_id` and `step_name`,
because they actually need no option. In this case, the suggestion is to
set them through `type`, like in the following example:

....
args:
  - type: step_id
  - type: step_name
  - path_cache: whatever
....

==== Setting defaults

If a dibspack is reused over and over (e.g. leveraging a suite of
dibspacks collected in a single git repository, much like
https://github.com/polettix/dibspack-basic[dibspack-basic], it comes
handy to set entries in the `defaults.dibspack` section of the
configuration file:

dibspack: basic: type: git origin:
https://github.com/polettix/dibspack-basic.git user: user prereqs: type:
git origin: https://github.com/polettix/dibspack-basic.git path: prereqs
user: root user: &user type: src name: add user and enable for docker
user: root path: dibspacks/user-docker.sh

and later use them, like this (leveraging YAML ancors):

....
definitions:
    builder:
        # ...
        dibspacks:
            - *user
....

or this, leveraging `dibs` internal system for handling defaults (via
the `default` keyword:

....
definitions:
    ...
  bundle:  
      dibspacks:
         - default: prereqs
           args: bundle
         - default: basic
           user: root
           path: wrapexec/install
           args: ['dockexec', 'profilexec']
         - default: basic
           path: install/plain-copy
           args: '@path_cache:perl-app /app'
           user: root
....

=== Environment Variables Handling

It is possible to specify environment variables in multiple places; the
following list gives the priority (the higher in the list, the more it
takes precedence):

* variables `DIBSPACK_FROM_IMAGE` and `DIBSPACK_WORK_IMAGE` are set by
`dibs` and indicate respectively the image in the `from` field of the
dibspack and its current alias (or evolution) in the dibs step
* other metadata dynamically generated by `dibs`, at the moment:
** `DIBS_ID`, generated from the timestamp and the `dibs` invocation
process id
* whatever appears in the dibspack’s `env` field
* whatever appears in the step’s `env` field
* whatever appears in the `default.env` section of the configuration
file.

Environment variaables can be specified in multiple ways:

* as lists of variables definition (recursive)
* as associative arrays: keys are environment variable names, values are
the associated values. Undefined values are taken from the `dibs`
environment.
* as plain scalars, which are interpreted as variable names whose value
is taken from the `dibs` environment.

Example:

....
default:
  env:
    - THIS
    - THAT: value
      ANOTHER: ~
definitions:
  first:
    env:
      - THIS: a-value
      - ANOTHER: some-value
    dibspacks:
      - name: dp1
        env:
          - THIS: different-value
        # ...
      - name: dp2
        env:
          - FOO: baz
  second:
    env:
      - FOO: bar
....

In this case:

* dibspack `dp1`:
** `THIS` takes value `different-value`
** `ANOTHER` takes value `some-value`
** `THAT` takes value `value`
* dibspack `dp2`:
** `THIS` takes value `a-value`
** `ANOTHER` takes value `some-value`
** `THAT` takes value `value`
** `FOO` takes value `baz`
* dibspacks in `second`:
** `THIS` takes value from `dibs`’s environment
** `ANOTHER` takes value from `dibs`’s environment
** `THAT` takes value `value`
** `FOO` takes value `bar`
