#!/usr/bin/env perl
use 5.024;
use warnings;
use Dibs::App 'main';
use Path::Tiny;

exit main(@ARGV);

sub version {
   my $version = $ENV{VERSION};

   if (! defined $version) {
      my $version_file = path(__FILE__)->sibling('VERSION');
      chomp($version = $version_file->slurp_utf8) if $version_file->exists;
   }

   # last resort, a default value
   $version //= '0.011972';

   for my $key (qw< GIT_REF DIBS_ID DIBS_FROM_IMAGE >) {
      next unless defined $ENV{$key};
      (my $name = lc $key) =~ s{_}{-}gmxs;
      $version .= " ($name $ENV{$key})";
   }

   return $version;
}

__END__
